<?php $this->headTitle('Home'); ?>

<div class="jumbotron">
    <h1>Welcome to <span class="api-tools-green">mezzio</span></h1>
    <p>
        Congratulations! You have successfully installed the
        <a href="https://github.com/mezzio/mezzio-skeleton" target="_blank">mezzio skeleton application</a>.
        This skeleton can serve as a simple starting point for you to begin building your application.
    </p>
    <p>
        Mezzio builds on laminas-stratigility to provide a minimalist PSR-7 middleware framework for PHP.
    </p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>
            <a href="https://mezzio.readthedocs.org/en/latest/features/" target="_blank">
                <i class="fa fa-refresh"></i> Agile &amp; Lean
            </a>
        </h2>
        <p>
            Mezzio is fast, small and perfect for rapid application development, prototyping and api's. You decide how you
            extend it and choose the best packages from major framework or standalone projects.
        </p>
    </div>

    <div class="col-md-4">
        <h2>
            <a href="https://github.com/laminas/laminas-diactoros" target="_blank">
                <i class="fa fa-exchange"></i> HTTP Messages
            </a>
        </h2>
        <p>
            HTTP messages are the foundation of web development. Web browsers and HTTP clients such as cURL create
            HTTP request messages that are sent to a web server, which provides an HTTP response message.
            Server-side code receives an HTTP request message, and returns an HTTP response message.
        </p>
    </div>

    <div class="col-md-4">
        <h2>
            <a href="https://github.com/laminas/laminas-stratigility" target="_blank">
                <i class="fa fa-dot-circle-o"></i> Middleware
            </a>
        </h2>
        <p>
            Middleware is code that exists between the request and response, and which can take the incoming
            request, perform actions based on it, and either complete the response or pass delegation on to the
            next middleware in the queue. Your application is easily extended with custom middleware created by
            yourself or <a href="https://packagist.org/search/?q=middleware" target="_blank">others</a>.
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>
            <a href="https://mezzio.readthedocs.org/en/latest/container/intro/" target="_blank">
                <i class="fa fa-cube"></i> Containers
            </a>
        </h2>
        <p>
            Mezzio promotes and advocates the usage of Dependency Injection/Inversion of Control containers
            when writing your applications. Mezzio supports multiple containers which typehints against
            <a href="https://github.com/container-interop/container-interop" target="_blank">container-interop</a>.
        </p>
    </div>

    <div class="col-md-4">
        <h2>
            <a href="<?php echo $this->routerDocsUrl ?>" target="_blank">
                <i class="fa fa-plane"></i> <?php echo $this->routerName ?>
            </a>
        </h2>
        <p>
            One fundamental feature of mezzio is that it provides mechanisms for implementing dynamic
            routing, a feature required in most modern web applications. Mezzio ships with multiple adapters.
            Learn more about <a href="<?php echo $this->routerExtUrl ?>" target="_blank"><?php echo $this->routerName ?></a>.
        </p>
    </div>

    <div class="col-md-4">
        <h2>
            <a href="https://mezzio.readthedocs.org/en/latest/template/laminas-view/" target="_blank">
                <i class="fa fa-files-o"></i> Laminas\View
            </a>
        </h2>
        <p>
            Laminas\View provides the View layer of Laminas's MVC system. It is a multi-tiered system
            allowing a variety of mechanisms for extension, substitution, and more.
            Learn more about <a href="https://docs.laminas.dev/laminas.view.quick-start.html" target="_blank">laminas-view</a>.
        </p>
    </div>
</div>
